jQuery(document).ready(function()
{
	jQuery("#wpwm_popClose").click(function()
	{
		jQuery("#wpwm_popBoxOut").slideUp();
		jQuery("#wpwm_popBox").slideUp();
		jQuery("#wpwm_hideBody").slideUp();
	});
	jQuery("#wpwm_hideBody").click(function()
	{
		jQuery("#wpwm_popBoxOut").slideUp();
		jQuery("#wpwm_popBox").slideUp();
		jQuery("#wpwm_hideBody").slideUp();
	});
});